(rule
 (targets ./conan_acorn.ml ./conan_adi.ml ./conan_adventure.ml
                ./conan_aes.ml ./conan_algol68.ml ./conan_allegro.ml
                ./conan_alliant.ml ./conan_alpha.ml ./conan_amanda.ml
                ./conan_amigaos.ml ./conan_android.ml ./conan_animation.ml
                ./conan_aout.ml ./conan_apache.ml ./conan_apl.ml
                ./conan_apple.ml ./conan_application.ml ./conan_applix.ml
                ./conan_apt.ml ./conan_archive.ml ./conan_aria.ml
                ./conan_arm.ml ./conan_asf.ml ./conan_assembler.ml
                ./conan_asterix.ml ./conan_att3b.ml ./conan_audio.ml
                ./conan_avm.ml ./conan_basis.ml ./conan_beetle.ml
                ./conan_ber.ml ./conan_bflt.ml ./conan_bhl.ml
                ./conan_bioinformatics.ml ./conan_biosig.ml
                ./conan_blackberry.ml ./conan_blcr.ml ./conan_blender.ml
                ./conan_blit.ml ./conan_bm.ml ./conan_bout.ml ./conan_bsdi.ml
                ./conan_bsi.ml ./conan_btsnoop.ml ./conan_burp.ml
                ./conan_bytecode.ml ./conan_c64.ml ./conan_c_lang.ml
                ./conan_cad.ml ./conan_cafebabe.ml ./conan_cbor.ml
                ./conan_ccf.ml ./conan_cddb.ml ./conan_chord.ml
                ./conan_cisco.ml ./conan_citrus.ml ./conan_clarion.ml
                ./conan_claris.ml ./conan_clipper.ml ./conan_clojure.ml
                ./conan_coff.ml ./conan_commands.ml ./conan_communications.ml
                ./conan_compress.ml ./conan_console.ml ./conan_convex.ml
                ./conan_coverage.ml ./conan_cracklib.ml ./conan_crypto.ml
                ./conan_ctags.ml ./conan_ctf.ml ./conan_cubemap.ml
                ./conan_cups.ml ./conan_dact.ml ./conan_database.ml
                ./conan_dataone.ml ./conan_dbpf.ml ./conan_der.ml
                ./conan_diamond.ml ./conan_dif.ml ./conan_diff.ml
                ./conan_digital.ml ./conan_dolby.ml ./conan_dump.ml
                ./conan_dwarfs.ml ./conan_dyadic.ml ./conan_ebml.ml
                ./conan_edid.ml ./conan_editors.ml ./conan_efi.ml
                ./conan_elf.ml ./conan_encore.ml ./conan_epoc.ml
                ./conan_erlang.ml ./conan_espressif.ml ./conan_esri.ml
                ./conan_etf.ml ./conan_fcs.ml ./conan_filesystems.ml
                ./conan_finger.ml ./conan_firmware.ml ./conan_flash.ml
                ./conan_flif.ml ./conan_fonts.ml ./conan_forth.ml
                ./conan_fortran.ml ./conan_frame.ml ./conan_freebsd.ml
                ./conan_fsav.ml ./conan_fusecompress.ml ./conan_games.ml
                ./conan_gcc.ml ./conan_gconv.ml ./conan_geo.ml
                ./conan_geos.ml ./conan_gimp.ml ./conan_git.ml
                ./conan_glibc.ml ./conan_gnome.ml ./conan_gnu.ml
                ./conan_gnumeric.ml ./conan_gpt.ml ./conan_gpu.ml
                ./conan_grace.ml ./conan_graphviz.ml ./conan_gringotts.ml
                ./conan_guile.ml ./conan_hardware.ml ./conan_hitachi_sh.ml
                ./conan_hp.ml ./conan_human68k.ml ./conan_ibm370.ml
                ./conan_ibm6000.ml ./conan_icc.ml ./conan_iff.ml
                ./conan_images.ml ./conan_inform.ml ./conan_intel.ml
                ./conan_interleaf.ml ./conan_island.ml ./conan_ispell.ml
                ./conan_isz.ml ./conan_java.ml ./conan_javascript.ml
                ./conan_jpeg.ml ./conan_karma.ml ./conan_kde.ml
                ./conan_keepass.ml ./conan_kerberos.ml ./conan_kicad.ml
                ./conan_kml.ml ./conan_lammps.ml ./conan_lecter.ml
                ./conan_lex.ml ./conan_lif.ml ./conan_light.ml
                ./conan_linux.ml ./conan_lisp.ml ./conan_llvm.ml
                ./conan_locoscript.ml ./conan_lua.ml ./conan_luks.ml
                ./conan_m4.ml ./conan_mach.ml ./conan_macintosh.ml
                ./conan_macos.ml ./conan_magic.ml ./conan_mail_news.ml
                ./conan_make.ml ./conan_map.ml ./conan_maple.ml
                ./conan_marc21.ml ./conan_mathcad.ml ./conan_mathematica.ml
                ./conan_matroska.ml ./conan_mcrypt.ml ./conan_measure.ml
                ./conan_mercurial.ml ./conan_metastore.ml
                ./conan_meteorological.ml ./conan_microfocus.ml
                ./conan_mime.ml ./conan_mips.ml ./conan_mirage.ml
                ./conan_misctools.ml ./conan_mkid.ml ./conan_mlssa.ml
                ./conan_mmdf.ml ./conan_modem.ml ./conan_modulefile.ml
                ./conan_motorola.ml ./conan_mozilla.ml ./conan_msdos.ml
                ./conan_msooxml.ml ./conan_msvc.ml ./conan_msx.ml
                ./conan_mup.ml ./conan_music.ml ./conan_nasa.ml
                ./conan_natinst.ml ./conan_ncr.ml ./conan_neko.ml
                ./conan_netbsd.ml ./conan_netscape.ml ./conan_netware.ml
                ./conan_news.ml ./conan_nifty.ml ./conan_nim_lang.ml
                ./conan_nitpicker.ml ./conan_numpy.ml ./conan_oasis.ml
                ./conan_ocaml.ml ./conan_octave.ml
                ./conan_ole2compounddocs.ml ./conan_olf.ml ./conan_openfst.ml
                ./conan_opentimestamps.ml ./conan_oric.ml ./conan_os2.ml
                ./conan_os400.ml ./conan_os9.ml ./conan_osf1.ml
                ./conan_palm.ml ./conan_parix.ml ./conan_parrot.ml
                ./conan_pascal.ml ./conan_pbf.ml ./conan_pbm.ml
                ./conan_pc88.ml ./conan_pc98.ml ./conan_pci_ids.ml
                ./conan_pcjr.ml ./conan_pdf.ml ./conan_pdp.ml ./conan_perl.ml
                ./conan_pgf.ml ./conan_pgp.ml ./conan_pgp_binary_keys.ml
                ./conan_pkgadd.ml ./conan_plan9.ml ./conan_playdate.ml
                ./conan_plus5.ml ./conan_pmem.ml ./conan_polyml.ml
                ./conan_printer.ml ./conan_project.ml ./conan_psdbms.ml
                ./conan_psl.ml ./conan_pulsar.ml ./conan_puzzle.ml
                ./conan_pwsafe.ml ./conan_pyramid.ml ./conan_python.ml
                ./conan_qt.ml ./conan_revision.ml ./conan_riff.ml
                ./conan_rinex.ml ./conan_ringdove.ml ./conan_rpi.ml
                ./conan_rpm.ml ./conan_rpmsg.ml ./conan_rst.ml ./conan_rtf.ml
                ./conan_ruby.ml ./conan_rust.ml ./conan_sc.ml ./conan_sccs.ml
                ./conan_scientific.ml ./conan_securitycerts.ml
                ./conan_selinux.ml ./conan_sendmail.ml ./conan_sequent.ml
                ./conan_sereal.ml ./conan_sgi.ml ./conan_sgml.ml
                ./conan_sharc.ml ./conan_sinclair.ml ./conan_sisu.ml
                ./conan_sketch.ml ./conan_smalltalk.ml ./conan_smile.ml
                ./conan_sniffer.ml ./conan_softquad.ml ./conan_sosi.ml
                ./conan_spec.ml ./conan_spectrum.ml ./conan_sql.ml
                ./conan_ssh.ml ./conan_ssl.ml ./conan_statistics.ml
                ./conan_subtitle.ml ./conan_sun.ml ./conan_svf.ml
                ./conan_sylk.ml ./conan_symbos.ml ./conan_sysex.ml
                ./conan_tcl.ml ./conan_teapot.ml ./conan_terminfo.ml
                ./conan_tex.ml ./conan_tgif.ml ./conan_ti_8x.ml
                ./conan_timezone.ml ./conan_tplink.ml ./conan_troff.ml
                ./conan_tuxedo.ml ./conan_typeset.ml ./conan_uf2.ml
                ./conan_unicode.ml ./conan_unisig.ml ./conan_unknown.ml
                ./conan_usd.ml ./conan_uterus.ml ./conan_uuencode.ml
                ./conan_vacuum_cleaner.ml ./conan_varied_out.ml
                ./conan_varied_script.ml ./conan_vax.ml ./conan_vicar.ml
                ./conan_virtual.ml ./conan_virtutech.ml ./conan_visx.ml
                ./conan_vms.ml ./conan_vmware.ml ./conan_vorbis.ml
                ./conan_vxl.ml ./conan_warc.ml ./conan_weak.ml ./conan_web.ml
                ./conan_webassembly.ml ./conan_windows.ml ./conan_wireless.ml
                ./conan_wordprocessors.ml ./conan_wsdl.ml ./conan_x68000.ml
                ./conan_xdelta.ml ./conan_xenix.ml ./conan_xilinx.ml
                ./conan_xo65.ml ./conan_xwindows.ml ./conan_yara.ml
                ./conan_zfs.ml ./conan_zilog.ml ./conan_zip.ml
                ./conan_zyxel.ml)
 (deps %{bin:conan.serialize} (source_tree ../database))
 (action
  (run conan.serialize --only-mime --name conan_light.ml ../database -o .)))

(rule
 (targets 
extensions.ml)
 (deps %{bin:conan.map} (source_tree ../database))
 (action
  (run conan.map --extension-to-mime ../database -o extensions.ml)))

(rule
 (targets 
mIMEs.ml)
 (deps %{bin:conan.map} (source_tree ../database))
 (action
  (run conan.map --mime-to-extension ../database -o mIMEs.ml)))

(library
 (name conan_light)
 (public_name conan-database.light)
 (wrapped false)
 (modules 
conan_acorn conan_adi conan_adventure conan_aes conan_algol68 conan_allegro
conan_alliant conan_alpha conan_amanda conan_amigaos conan_android
conan_animation conan_aout conan_apache conan_apl conan_apple
conan_application conan_applix conan_apt conan_archive conan_aria conan_arm
conan_asf conan_assembler conan_asterix conan_att3b conan_audio conan_avm
conan_basis conan_beetle conan_ber conan_bflt conan_bhl conan_bioinformatics
conan_biosig conan_blackberry conan_blcr conan_blender conan_blit conan_bm
conan_bout conan_bsdi conan_bsi conan_btsnoop conan_burp conan_bytecode
conan_c64 conan_c_lang conan_cad conan_cafebabe conan_cbor conan_ccf
conan_cddb conan_chord conan_cisco conan_citrus conan_clarion conan_claris
conan_clipper conan_clojure conan_coff conan_commands conan_communications
conan_compress conan_console conan_convex conan_coverage conan_cracklib
conan_crypto conan_ctags conan_ctf conan_cubemap conan_cups conan_dact
conan_database conan_dataone conan_dbpf conan_der conan_diamond conan_dif
conan_diff conan_digital conan_dolby conan_dump conan_dwarfs conan_dyadic
conan_ebml conan_edid conan_editors conan_efi conan_elf conan_encore
conan_epoc conan_erlang conan_espressif conan_esri conan_etf conan_fcs
conan_filesystems conan_finger conan_firmware conan_flash conan_flif
conan_fonts conan_forth conan_fortran conan_frame conan_freebsd conan_fsav
conan_fusecompress conan_games conan_gcc conan_gconv conan_geo conan_geos
conan_gimp conan_git conan_glibc conan_gnome conan_gnu conan_gnumeric
conan_gpt conan_gpu conan_grace conan_graphviz conan_gringotts conan_guile
conan_hardware conan_hitachi_sh conan_hp conan_human68k conan_ibm370
conan_ibm6000 conan_icc conan_iff conan_images conan_inform conan_intel
conan_interleaf conan_island conan_ispell conan_isz conan_java
conan_javascript conan_jpeg conan_karma conan_kde conan_keepass
conan_kerberos conan_kicad conan_kml conan_lammps conan_lecter conan_lex
conan_lif conan_light conan_linux conan_lisp conan_llvm conan_locoscript
conan_lua conan_luks conan_m4 conan_mach conan_macintosh conan_macos
conan_magic conan_mail_news conan_make conan_map conan_maple conan_marc21
conan_mathcad conan_mathematica conan_matroska conan_mcrypt conan_measure
conan_mercurial conan_metastore conan_meteorological conan_microfocus
conan_mime conan_mips conan_mirage conan_misctools conan_mkid conan_mlssa
conan_mmdf conan_modem conan_modulefile conan_motorola conan_mozilla
conan_msdos conan_msooxml conan_msvc conan_msx conan_mup conan_music
conan_nasa conan_natinst conan_ncr conan_neko conan_netbsd conan_netscape
conan_netware conan_news conan_nifty conan_nim_lang conan_nitpicker
conan_numpy conan_oasis conan_ocaml conan_octave conan_ole2compounddocs
conan_olf conan_openfst conan_opentimestamps conan_oric conan_os2 conan_os400
conan_os9 conan_osf1 conan_palm conan_parix conan_parrot conan_pascal
conan_pbf conan_pbm conan_pc88 conan_pc98 conan_pci_ids conan_pcjr conan_pdf
conan_pdp conan_perl conan_pgf conan_pgp conan_pgp_binary_keys conan_pkgadd
conan_plan9 conan_playdate conan_plus5 conan_pmem conan_polyml conan_printer
conan_project conan_psdbms conan_psl conan_pulsar conan_puzzle conan_pwsafe
conan_pyramid conan_python conan_qt conan_revision conan_riff conan_rinex
conan_ringdove conan_rpi conan_rpm conan_rpmsg conan_rst conan_rtf conan_ruby
conan_rust conan_sc conan_sccs conan_scientific conan_securitycerts
conan_selinux conan_sendmail conan_sequent conan_sereal conan_sgi conan_sgml
conan_sharc conan_sinclair conan_sisu conan_sketch conan_smalltalk
conan_smile conan_sniffer conan_softquad conan_sosi conan_spec conan_spectrum
conan_sql conan_ssh conan_ssl conan_statistics conan_subtitle conan_sun
conan_svf conan_sylk conan_symbos conan_sysex conan_tcl conan_teapot
conan_terminfo conan_tex conan_tgif conan_ti_8x conan_timezone conan_tplink
conan_troff conan_tuxedo conan_typeset conan_uf2 conan_unicode conan_unisig
conan_unknown conan_usd conan_uterus conan_uuencode conan_vacuum_cleaner
conan_varied_out conan_varied_script conan_vax conan_vicar conan_virtual
conan_virtutech conan_visx conan_vms conan_vmware conan_vorbis conan_vxl
conan_warc conan_weak conan_web conan_webassembly conan_windows
conan_wireless conan_wordprocessors conan_wsdl conan_x68000 conan_xdelta
conan_xenix conan_xilinx conan_xo65 conan_xwindows conan_yara conan_zfs
conan_zilog conan_zip conan_zyxel)
 (libraries conan))

(library
 (name conan_bindings)
 (public_name conan-database.bindings)
 (modules 
conan_bindings mIMEs extensions))
