(rule
 (targets ./acorn.ml ./adi.ml ./adventure.ml ./aes.ml ./algol68.ml
                ./allegro.ml ./alliant.ml ./alpha.ml ./amanda.ml ./amigaos.ml
                ./android.ml ./animation.ml ./aout.ml ./apache.ml ./apl.ml
                ./apple.ml ./application.ml ./applix.ml ./apt.ml ./archive.ml
                ./arm.ml ./asf.ml ./assembler.ml ./asterix.ml ./att3b.ml
                ./audio.ml ./avm.ml ./basis.ml ./beetle.ml ./ber.ml ./bflt.ml
                ./bhl.ml ./bioinformatics.ml ./biosig.ml ./blackberry.ml
                ./blcr.ml ./blender.ml ./blit.ml ./bm.ml ./bout.ml ./bsdi.ml
                ./bsi.ml ./btsnoop.ml ./bytecode.ml ./c64.ml ./c_lang.ml
                ./cad.ml ./cafebabe.ml ./cbor.ml ./cddb.ml ./chord.ml
                ./cisco.ml ./citrus.ml ./clarion.ml ./claris.ml ./clipper.ml
                ./clojure.ml ./coff.ml ./commands.ml ./communications.ml
                ./compress.ml ./conan_database.ml ./console.ml ./convex.ml
                ./coverage.ml ./cracklib.ml ./crypto.ml ./ctags.ml ./ctf.ml
                ./cubemap.ml ./cups.ml ./dact.ml ./database.ml ./dataone.ml
                ./dbpf.ml ./der.ml ./diamond.ml ./dif.ml ./diff.ml
                ./digital.ml ./dolby.ml ./dump.ml ./dyadic.ml ./ebml.ml
                ./edid.ml ./editors.ml ./efi.ml ./elf.ml ./encore.ml
                ./epoc.ml ./erlang.ml ./espressif.ml ./esri.ml ./etf.ml
                ./fcs.ml ./filesystems.ml ./filesystems_000.ml
                ./filesystems_001.ml ./filesystems_002.ml
                ./filesystems_003.ml ./filesystems_004.ml
                ./filesystems_005.ml ./filesystems_006.ml
                ./filesystems_007.ml ./filesystems_008.ml
                ./filesystems_009.ml ./filesystems_010.ml
                ./filesystems_011.ml ./filesystems_012.ml
                ./filesystems_013.ml ./filesystems_014.ml
                ./filesystems_015.ml ./filesystems_016.ml
                ./filesystems_017.ml ./filesystems_018.ml
                ./filesystems_019.ml ./filesystems_020.ml
                ./filesystems_021.ml ./filesystems_022.ml
                ./filesystems_023.ml ./filesystems_024.ml
                ./filesystems_025.ml ./filesystems_026.ml
                ./filesystems_027.ml ./filesystems_028.ml
                ./filesystems_029.ml ./filesystems_030.ml
                ./filesystems_031.ml ./filesystems_032.ml
                ./filesystems_033.ml ./filesystems_034.ml
                ./filesystems_035.ml ./filesystems_036.ml
                ./filesystems_037.ml ./filesystems_038.ml
                ./filesystems_039.ml ./filesystems_040.ml
                ./filesystems_041.ml ./filesystems_042.ml
                ./filesystems_043.ml ./filesystems_044.ml
                ./filesystems_045.ml ./filesystems_046.ml
                ./filesystems_047.ml ./filesystems_048.ml
                ./filesystems_049.ml ./filesystems_050.ml
                ./filesystems_051.ml ./filesystems_052.ml
                ./filesystems_053.ml ./filesystems_054.ml
                ./filesystems_055.ml ./filesystems_056.ml
                ./filesystems_057.ml ./filesystems_058.ml
                ./filesystems_059.ml ./filesystems_060.ml
                ./filesystems_061.ml ./filesystems_062.ml
                ./filesystems_063.ml ./filesystems_064.ml
                ./filesystems_065.ml ./filesystems_066.ml
                ./filesystems_067.ml ./filesystems_068.ml
                ./filesystems_069.ml ./filesystems_070.ml
                ./filesystems_071.ml ./filesystems_072.ml
                ./filesystems_073.ml ./filesystems_074.ml
                ./filesystems_075.ml ./filesystems_076.ml
                ./filesystems_077.ml ./filesystems_078.ml
                ./filesystems_079.ml ./filesystems_080.ml
                ./filesystems_081.ml ./filesystems_082.ml
                ./filesystems_083.ml ./filesystems_084.ml
                ./filesystems_085.ml ./filesystems_086.ml
                ./filesystems_087.ml ./filesystems_088.ml
                ./filesystems_089.ml ./filesystems_090.ml
                ./filesystems_091.ml ./filesystems_092.ml
                ./filesystems_093.ml ./filesystems_094.ml
                ./filesystems_095.ml ./filesystems_096.ml
                ./filesystems_097.ml ./filesystems_098.ml
                ./filesystems_099.ml ./filesystems_100.ml
                ./filesystems_101.ml ./filesystems_102.ml
                ./filesystems_103.ml ./filesystems_104.ml
                ./filesystems_105.ml ./filesystems_106.ml
                ./filesystems_107.ml ./filesystems_108.ml
                ./filesystems_109.ml ./filesystems_110.ml
                ./filesystems_111.ml ./filesystems_112.ml
                ./filesystems_113.ml ./filesystems_114.ml
                ./filesystems_115.ml ./filesystems_116.ml
                ./filesystems_117.ml ./filesystems_118.ml
                ./filesystems_119.ml ./filesystems_120.ml
                ./filesystems_121.ml ./filesystems_122.ml
                ./filesystems_123.ml ./filesystems_124.ml
                ./filesystems_125.ml ./finger.ml ./flash.ml ./flif.ml
                ./fonts.ml ./forth.ml ./fortran.ml ./frame.ml ./freebsd.ml
                ./fsav.ml ./fusecompress.ml ./games.ml ./gcc.ml ./gconv.ml
                ./geo.ml ./geos.ml ./gimp.ml ./git.ml ./glibc.ml ./gnome.ml
                ./gnu.ml ./gnumeric.ml ./gpt.ml ./gpu.ml ./grace.ml
                ./graphviz.ml ./gringotts.ml ./guile.ml ./hardware.ml
                ./hitachi_sh.ml ./hp.ml ./human68k.ml ./ibm370.ml
                ./ibm6000.ml ./icc.ml ./iff.ml ./images.ml ./images_000.ml
                ./images_001.ml ./images_002.ml ./images_003.ml
                ./images_004.ml ./images_005.ml ./images_006.ml
                ./images_007.ml ./images_008.ml ./images_009.ml
                ./images_010.ml ./images_011.ml ./images_012.ml
                ./images_013.ml ./images_014.ml ./images_015.ml
                ./images_016.ml ./images_017.ml ./images_018.ml
                ./images_019.ml ./images_020.ml ./images_021.ml
                ./images_022.ml ./images_023.ml ./images_024.ml
                ./images_025.ml ./images_026.ml ./images_027.ml
                ./images_028.ml ./images_029.ml ./images_030.ml
                ./images_031.ml ./images_032.ml ./images_033.ml
                ./images_034.ml ./images_035.ml ./images_036.ml
                ./images_037.ml ./images_038.ml ./images_039.ml
                ./images_040.ml ./images_041.ml ./images_042.ml
                ./images_043.ml ./images_044.ml ./images_045.ml
                ./images_046.ml ./images_047.ml ./images_048.ml
                ./images_049.ml ./images_050.ml ./images_051.ml
                ./images_052.ml ./images_053.ml ./images_054.ml
                ./images_055.ml ./images_056.ml ./images_057.ml
                ./images_058.ml ./images_059.ml ./images_060.ml
                ./images_061.ml ./images_062.ml ./images_063.ml
                ./images_064.ml ./images_065.ml ./images_066.ml
                ./images_067.ml ./images_068.ml ./images_069.ml
                ./images_070.ml ./images_071.ml ./images_072.ml
                ./images_073.ml ./images_074.ml ./images_075.ml
                ./images_076.ml ./images_077.ml ./images_078.ml
                ./images_079.ml ./images_080.ml ./images_081.ml
                ./images_082.ml ./images_083.ml ./images_084.ml
                ./images_085.ml ./images_086.ml ./images_087.ml
                ./images_088.ml ./images_089.ml ./images_090.ml
                ./images_091.ml ./images_092.ml ./images_093.ml
                ./images_094.ml ./images_095.ml ./images_096.ml
                ./images_097.ml ./images_098.ml ./images_099.ml
                ./images_100.ml ./images_101.ml ./images_102.ml
                ./images_103.ml ./images_104.ml ./images_105.ml
                ./images_106.ml ./images_107.ml ./images_108.ml
                ./images_109.ml ./images_110.ml ./images_111.ml
                ./images_112.ml ./images_113.ml ./images_114.ml
                ./images_115.ml ./images_116.ml ./images_117.ml
                ./images_118.ml ./images_119.ml ./images_120.ml
                ./images_121.ml ./images_122.ml ./images_123.ml
                ./images_124.ml ./images_125.ml ./images_126.ml
                ./images_127.ml ./images_128.ml ./images_129.ml
                ./images_130.ml ./images_131.ml ./images_132.ml
                ./images_133.ml ./images_134.ml ./images_135.ml
                ./images_136.ml ./images_137.ml ./images_138.ml
                ./images_139.ml ./images_140.ml ./images_141.ml
                ./images_142.ml ./images_143.ml ./images_144.ml
                ./images_145.ml ./images_146.ml ./images_147.ml
                ./images_148.ml ./images_149.ml ./images_150.ml
                ./images_151.ml ./images_152.ml ./images_153.ml
                ./images_154.ml ./images_155.ml ./images_156.ml
                ./images_157.ml ./images_158.ml ./images_159.ml
                ./images_160.ml ./images_161.ml ./images_162.ml
                ./images_163.ml ./images_164.ml ./images_165.ml
                ./images_166.ml ./images_167.ml ./images_168.ml
                ./images_169.ml ./images_170.ml ./images_171.ml
                ./images_172.ml ./images_173.ml ./images_174.ml
                ./images_175.ml ./images_176.ml ./images_177.ml
                ./images_178.ml ./images_179.ml ./images_180.ml
                ./images_181.ml ./images_182.ml ./images_183.ml
                ./images_184.ml ./images_185.ml ./images_186.ml
                ./images_187.ml ./images_188.ml ./images_189.ml
                ./images_190.ml ./images_191.ml ./images_192.ml
                ./images_193.ml ./images_194.ml ./images_195.ml ./inform.ml
                ./intel.ml ./interleaf.ml ./island.ml ./ispell.ml ./isz.ml
                ./java.ml ./javascript.ml ./jpeg.ml ./karma.ml ./kde.ml
                ./keepass.ml ./kerberos.ml ./kicad.ml ./kml.ml ./lammps.ml
                ./lecter.ml ./lex.ml ./lif.ml ./linux.ml ./lisp.ml ./llvm.ml
                ./locoscript.ml ./lua.ml ./luks.ml ./m4.ml ./mach.ml
                ./macintosh.ml ./macos.ml ./magic.ml ./mail_news.ml ./make.ml
                ./map.ml ./maple.ml ./marc21.ml ./mathcad.ml ./mathematica.ml
                ./matroska.ml ./mcrypt.ml ./measure.ml ./mercurial.ml
                ./metastore.ml ./meteorological.ml ./microfocus.ml ./mime.ml
                ./mips.ml ./mirage.ml ./misctools.ml ./mkid.ml ./mlssa.ml
                ./mmdf.ml ./modem.ml ./modulefile.ml ./motorola.ml
                ./mozilla.ml ./msdos.ml ./msooxml.ml ./msvc.ml ./msx.ml
                ./mup.ml ./music.ml ./nasa.ml ./natinst.ml ./ncr.ml ./neko.ml
                ./netbsd.ml ./netscape.ml ./netware.ml ./news.ml
                ./nim_lang.ml ./nitpicker.ml ./numpy.ml ./oasis.ml ./ocaml.ml
                ./octave.ml ./ole2compounddocs.ml ./olf.ml ./openfst.ml
                ./opentimestamps.ml ./os2.ml ./os400.ml ./os9.ml ./osf1.ml
                ./palm.ml ./parix.ml ./parrot.ml ./pascal.ml ./pbf.ml
                ./pbm.ml ./pc88.ml ./pc98.ml ./pcjr.ml ./pdf.ml ./pdp.ml
                ./perl.ml ./pgf.ml ./pgp.ml ./pgp_binary_keys.ml ./pkgadd.ml
                ./plan9.ml ./plus5.ml ./pmem.ml ./polyml.ml ./printer.ml
                ./project.ml ./psdbms.ml ./psl.ml ./pulsar.ml ./puzzle.ml
                ./pwsafe.ml ./pyramid.ml ./python.ml ./qt.ml ./revision.ml
                ./riff.ml ./rinex.ml ./rpi.ml ./rpm.ml ./rpmsg.ml ./rst.ml
                ./rtf.ml ./ruby.ml ./sc.ml ./sccs.ml ./scientific.ml
                ./securitycerts.ml ./selinux.ml ./sendmail.ml ./sequent.ml
                ./sereal.ml ./sgi.ml ./sgml.ml ./sharc.ml ./sinclair.ml
                ./sisu.ml ./sketch.ml ./smalltalk.ml ./smile.ml ./sniffer.ml
                ./softquad.ml ./sosi.ml ./spec.ml ./spectrum.ml ./sql.ml
                ./ssh.ml ./ssl.ml ./statistics.ml ./sun.ml ./sylk.ml
                ./symbos.ml ./sysex.ml ./tcl.ml ./teapot.ml ./terminfo.ml
                ./tex.ml ./tgif.ml ./ti_8x.ml ./timezone.ml ./tplink.ml
                ./troff.ml ./tuxedo.ml ./typeset.ml ./uf2.ml ./unicode.ml
                ./unisig.ml ./unknown.ml ./usd.ml ./uterus.ml ./uuencode.ml
                ./vacuum_cleaner.ml ./varied_out.ml ./varied_script.ml
                ./vax.ml ./vicar.ml ./virtual'.ml ./virtutech.ml ./visx.ml
                ./vms.ml ./vmware.ml ./vorbis.ml ./vxl.ml ./warc.ml ./weak.ml
                ./web.ml ./webassembly.ml ./windows.ml ./wireless.ml
                ./wordprocessors.ml ./wsdl.ml ./x68000.ml ./xdelta.ml
                ./xenix.ml ./xilinx.ml ./xo65.ml ./xwindows.ml ./yara.ml
                ./zfs.ml ./zilog.ml ./zip.ml ./zyxel.ml)
 (deps %{bin:conan.serialize} (source_tree ../database))
 (action
  (run conan.serialize ../database -o .)))

(library
 (name conan_database)
 (public_name conan-database)
 (modules 
acorn adi adventure aes algol68 allegro alliant alpha amanda amigaos android
animation aout apache apl apple application applix apt archive arm asf
assembler asterix att3b audio avm basis beetle ber bflt bhl bioinformatics
biosig blackberry blcr blender blit bm bout bsdi bsi btsnoop bytecode c64
c_lang cad cafebabe cbor cddb chord cisco citrus clarion claris clipper
clojure coff commands communications compress conan_database console convex
coverage cracklib crypto ctags ctf cubemap cups dact database dataone dbpf
der diamond dif diff digital dolby dump dyadic ebml edid editors efi elf
encore epoc erlang espressif esri etf fcs filesystems filesystems_000
filesystems_001 filesystems_002 filesystems_003 filesystems_004
filesystems_005 filesystems_006 filesystems_007 filesystems_008
filesystems_009 filesystems_010 filesystems_011 filesystems_012
filesystems_013 filesystems_014 filesystems_015 filesystems_016
filesystems_017 filesystems_018 filesystems_019 filesystems_020
filesystems_021 filesystems_022 filesystems_023 filesystems_024
filesystems_025 filesystems_026 filesystems_027 filesystems_028
filesystems_029 filesystems_030 filesystems_031 filesystems_032
filesystems_033 filesystems_034 filesystems_035 filesystems_036
filesystems_037 filesystems_038 filesystems_039 filesystems_040
filesystems_041 filesystems_042 filesystems_043 filesystems_044
filesystems_045 filesystems_046 filesystems_047 filesystems_048
filesystems_049 filesystems_050 filesystems_051 filesystems_052
filesystems_053 filesystems_054 filesystems_055 filesystems_056
filesystems_057 filesystems_058 filesystems_059 filesystems_060
filesystems_061 filesystems_062 filesystems_063 filesystems_064
filesystems_065 filesystems_066 filesystems_067 filesystems_068
filesystems_069 filesystems_070 filesystems_071 filesystems_072
filesystems_073 filesystems_074 filesystems_075 filesystems_076
filesystems_077 filesystems_078 filesystems_079 filesystems_080
filesystems_081 filesystems_082 filesystems_083 filesystems_084
filesystems_085 filesystems_086 filesystems_087 filesystems_088
filesystems_089 filesystems_090 filesystems_091 filesystems_092
filesystems_093 filesystems_094 filesystems_095 filesystems_096
filesystems_097 filesystems_098 filesystems_099 filesystems_100
filesystems_101 filesystems_102 filesystems_103 filesystems_104
filesystems_105 filesystems_106 filesystems_107 filesystems_108
filesystems_109 filesystems_110 filesystems_111 filesystems_112
filesystems_113 filesystems_114 filesystems_115 filesystems_116
filesystems_117 filesystems_118 filesystems_119 filesystems_120
filesystems_121 filesystems_122 filesystems_123 filesystems_124
filesystems_125 finger flash flif fonts forth fortran frame freebsd fsav
fusecompress games gcc gconv geo geos gimp git glibc gnome gnu gnumeric gpt
gpu grace graphviz gringotts guile hardware hitachi_sh hp human68k ibm370
ibm6000 icc iff images images_000 images_001 images_002 images_003 images_004
images_005 images_006 images_007 images_008 images_009 images_010 images_011
images_012 images_013 images_014 images_015 images_016 images_017 images_018
images_019 images_020 images_021 images_022 images_023 images_024 images_025
images_026 images_027 images_028 images_029 images_030 images_031 images_032
images_033 images_034 images_035 images_036 images_037 images_038 images_039
images_040 images_041 images_042 images_043 images_044 images_045 images_046
images_047 images_048 images_049 images_050 images_051 images_052 images_053
images_054 images_055 images_056 images_057 images_058 images_059 images_060
images_061 images_062 images_063 images_064 images_065 images_066 images_067
images_068 images_069 images_070 images_071 images_072 images_073 images_074
images_075 images_076 images_077 images_078 images_079 images_080 images_081
images_082 images_083 images_084 images_085 images_086 images_087 images_088
images_089 images_090 images_091 images_092 images_093 images_094 images_095
images_096 images_097 images_098 images_099 images_100 images_101 images_102
images_103 images_104 images_105 images_106 images_107 images_108 images_109
images_110 images_111 images_112 images_113 images_114 images_115 images_116
images_117 images_118 images_119 images_120 images_121 images_122 images_123
images_124 images_125 images_126 images_127 images_128 images_129 images_130
images_131 images_132 images_133 images_134 images_135 images_136 images_137
images_138 images_139 images_140 images_141 images_142 images_143 images_144
images_145 images_146 images_147 images_148 images_149 images_150 images_151
images_152 images_153 images_154 images_155 images_156 images_157 images_158
images_159 images_160 images_161 images_162 images_163 images_164 images_165
images_166 images_167 images_168 images_169 images_170 images_171 images_172
images_173 images_174 images_175 images_176 images_177 images_178 images_179
images_180 images_181 images_182 images_183 images_184 images_185 images_186
images_187 images_188 images_189 images_190 images_191 images_192 images_193
images_194 images_195 inform intel interleaf island ispell isz java
javascript jpeg karma kde keepass kerberos kicad kml lammps lecter lex lif
linux lisp llvm locoscript lua luks m4 mach macintosh macos magic mail_news
make map maple marc21 mathcad mathematica matroska mcrypt measure mercurial
metastore meteorological microfocus mime mips mirage misctools mkid mlssa
mmdf modem modulefile motorola mozilla msdos msooxml msvc msx mup music nasa
natinst ncr neko netbsd netscape netware news nim_lang nitpicker numpy oasis
ocaml octave ole2compounddocs olf openfst opentimestamps os2 os400 os9 osf1
palm parix parrot pascal pbf pbm pc88 pc98 pcjr pdf pdp perl pgf pgp
pgp_binary_keys pkgadd plan9 plus5 pmem polyml printer project psdbms psl
pulsar puzzle pwsafe pyramid python qt revision riff rinex rpi rpm rpmsg rst
rtf ruby sc sccs scientific securitycerts selinux sendmail sequent sereal sgi
sgml sharc sinclair sisu sketch smalltalk smile sniffer softquad sosi spec
spectrum sql ssh ssl statistics sun sylk symbos sysex tcl teapot terminfo tex
tgif ti_8x timezone tplink troff tuxedo typeset uf2 unicode unisig unknown
usd uterus uuencode vacuum_cleaner varied_out varied_script vax vicar
virtual' virtutech visx vms vmware vorbis vxl warc weak web webassembly
windows wireless wordprocessors wsdl x68000 xdelta xenix xilinx xo65 xwindows
yara zfs zilog zip zyxel)
 (libraries conan))
