(rule
 (targets ./conan_database.ml ./blackberry.ml ./os2.ml ./bout.ml
                ./kerberos.ml ./os400.ml ./diamond.ml ./amigaos.ml
                ./graphviz.ml ./uterus.ml ./cad.ml ./cisco.ml ./macintosh.ml
                ./cups.ml ./zilog.ml ./clarion.ml ./mathcad.ml ./ibm6000.ml
                ./motorola.ml ./efi.ml ./virtutech.ml ./clipper.ml ./flif.ml
                ./xilinx.ml ./c_lang.ml ./symbos.ml ./finger.ml ./vxl.ml
                ./dataone.ml ./sql.ml ./pascal.ml ./modulefile.ml ./teapot.ml
                ./forth.ml ./news.ml ./virtual'.ml ./images.ml
                ./images_000.ml ./images_001.ml ./images_002.ml
                ./images_003.ml ./images_004.ml ./images_005.ml
                ./images_006.ml ./images_007.ml ./images_008.ml
                ./images_009.ml ./images_010.ml ./images_011.ml
                ./images_012.ml ./images_013.ml ./images_014.ml
                ./images_015.ml ./images_016.ml ./images_017.ml
                ./images_018.ml ./images_019.ml ./images_020.ml
                ./images_021.ml ./images_022.ml ./images_023.ml
                ./images_024.ml ./images_025.ml ./images_026.ml
                ./images_027.ml ./images_028.ml ./images_029.ml
                ./images_030.ml ./images_031.ml ./images_032.ml
                ./images_033.ml ./images_034.ml ./images_035.ml
                ./images_036.ml ./images_037.ml ./images_038.ml
                ./images_039.ml ./images_040.ml ./images_041.ml
                ./images_042.ml ./images_043.ml ./images_044.ml
                ./images_045.ml ./images_046.ml ./images_047.ml
                ./images_048.ml ./images_049.ml ./images_050.ml
                ./images_051.ml ./images_052.ml ./images_053.ml
                ./images_054.ml ./images_055.ml ./images_056.ml
                ./images_057.ml ./images_058.ml ./images_059.ml
                ./images_060.ml ./images_061.ml ./images_062.ml
                ./images_063.ml ./images_064.ml ./images_065.ml
                ./images_066.ml ./images_067.ml ./images_068.ml
                ./images_069.ml ./images_070.ml ./images_071.ml
                ./images_072.ml ./images_073.ml ./images_074.ml
                ./images_075.ml ./images_076.ml ./images_077.ml
                ./images_078.ml ./images_079.ml ./images_080.ml
                ./images_081.ml ./images_082.ml ./images_083.ml
                ./images_084.ml ./images_085.ml ./images_086.ml
                ./images_087.ml ./images_088.ml ./images_089.ml
                ./images_090.ml ./images_091.ml ./images_092.ml
                ./images_093.ml ./images_094.ml ./images_095.ml
                ./images_096.ml ./images_097.ml ./images_098.ml
                ./images_099.ml ./images_100.ml ./images_101.ml
                ./images_102.ml ./images_103.ml ./images_104.ml
                ./images_105.ml ./images_106.ml ./images_107.ml
                ./images_108.ml ./images_109.ml ./images_110.ml
                ./images_111.ml ./images_112.ml ./images_113.ml
                ./images_114.ml ./images_115.ml ./images_116.ml
                ./images_117.ml ./images_118.ml ./images_119.ml
                ./images_120.ml ./images_121.ml ./images_122.ml
                ./images_123.ml ./images_124.ml ./images_125.ml
                ./images_126.ml ./images_127.ml ./images_128.ml
                ./images_129.ml ./images_130.ml ./images_131.ml
                ./images_132.ml ./images_133.ml ./images_134.ml
                ./images_135.ml ./images_136.ml ./images_137.ml
                ./images_138.ml ./images_139.ml ./images_140.ml
                ./images_141.ml ./images_142.ml ./images_143.ml
                ./images_144.ml ./images_145.ml ./images_146.ml
                ./images_147.ml ./images_148.ml ./images_149.ml
                ./images_150.ml ./images_151.ml ./images_152.ml
                ./images_153.ml ./images_154.ml ./images_155.ml
                ./images_156.ml ./images_157.ml ./images_158.ml
                ./images_159.ml ./images_160.ml ./images_161.ml
                ./images_162.ml ./images_163.ml ./images_164.ml
                ./images_165.ml ./images_166.ml ./images_167.ml
                ./images_168.ml ./images_169.ml ./images_170.ml
                ./images_171.ml ./images_172.ml ./images_173.ml
                ./images_174.ml ./bsdi.ml ./rtf.ml ./freebsd.ml ./visx.ml
                ./flash.ml ./mkid.ml ./metastore.ml ./bflt.ml ./palm.ml
                ./intel.ml ./ctags.ml ./esri.ml ./dump.ml ./interleaf.ml
                ./adventure.ml ./animation.ml ./adi.ml ./sinclair.ml
                ./matroska.ml ./geos.ml ./netscape.ml ./algol68.ml
                ./digital.ml ./mup.ml ./gconv.ml ./lif.ml ./asterix.ml
                ./natinst.ml ./apache.ml ./cafebabe.ml ./dolby.ml ./bhl.ml
                ./iff.ml ./icc.ml ./mlssa.ml ./karma.ml ./kml.ml ./selinux.ml
                ./python.ml ./perl.ml ./pyramid.ml ./msdos.ml ./games.ml
                ./ncr.ml ./smalltalk.ml ./weak.ml ./dbpf.ml ./assembler.ml
                ./mirage.ml ./os9.ml ./ssl.ml ./revision.ml ./map.ml
                ./polyml.ml ./diff.ml ./smile.ml ./maple.ml ./der.ml
                ./encore.ml ./etf.ml ./securitycerts.ml ./espressif.ml
                ./typeset.ml ./pulsar.ml ./opentimestamps.ml ./pgf.ml
                ./allegro.ml ./x68000.ml ./sereal.ml ./aout.ml ./pbm.ml
                ./rpm.ml ./kde.ml ./netbsd.ml ./alpha.ml ./javascript.ml
                ./vorbis.ml ./android.ml ./gringotts.ml ./applix.ml
                ./tuxedo.ml ./pdf.ml ./gnome.ml ./sun.ml ./ber.ml ./xo65.ml
                ./gpu.ml ./project.ml ./filesystems.ml ./filesystems_000.ml
                ./filesystems_001.ml ./filesystems_002.ml
                ./filesystems_003.ml ./filesystems_004.ml
                ./filesystems_005.ml ./filesystems_006.ml
                ./filesystems_007.ml ./filesystems_008.ml
                ./filesystems_009.ml ./filesystems_010.ml
                ./filesystems_011.ml ./filesystems_012.ml
                ./filesystems_013.ml ./filesystems_014.ml
                ./filesystems_015.ml ./filesystems_016.ml
                ./filesystems_017.ml ./filesystems_018.ml
                ./filesystems_019.ml ./filesystems_020.ml
                ./filesystems_021.ml ./filesystems_022.ml
                ./filesystems_023.ml ./filesystems_024.ml
                ./filesystems_025.ml ./filesystems_026.ml
                ./filesystems_027.ml ./filesystems_028.ml
                ./filesystems_029.ml ./filesystems_030.ml
                ./filesystems_031.ml ./filesystems_032.ml
                ./filesystems_033.ml ./filesystems_034.ml
                ./filesystems_035.ml ./filesystems_036.ml
                ./filesystems_037.ml ./filesystems_038.ml
                ./filesystems_039.ml ./filesystems_040.ml
                ./filesystems_041.ml ./filesystems_042.ml
                ./filesystems_043.ml ./filesystems_044.ml
                ./filesystems_045.ml ./filesystems_046.ml
                ./filesystems_047.ml ./filesystems_048.ml
                ./filesystems_049.ml ./filesystems_050.ml
                ./filesystems_051.ml ./filesystems_052.ml
                ./filesystems_053.ml ./filesystems_054.ml
                ./filesystems_055.ml ./filesystems_056.ml
                ./filesystems_057.ml ./filesystems_058.ml
                ./filesystems_059.ml ./filesystems_060.ml
                ./filesystems_061.ml ./filesystems_062.ml
                ./filesystems_063.ml ./filesystems_064.ml
                ./filesystems_065.ml ./filesystems_066.ml
                ./filesystems_067.ml ./filesystems_068.ml
                ./filesystems_069.ml ./filesystems_070.ml
                ./filesystems_071.ml ./filesystems_072.ml
                ./filesystems_073.ml ./filesystems_074.ml
                ./filesystems_075.ml ./filesystems_076.ml
                ./filesystems_077.ml ./filesystems_078.ml
                ./filesystems_079.ml ./filesystems_080.ml
                ./filesystems_081.ml ./filesystems_082.ml
                ./filesystems_083.ml ./filesystems_084.ml
                ./filesystems_085.ml ./filesystems_086.ml
                ./filesystems_087.ml ./filesystems_088.ml
                ./filesystems_089.ml ./filesystems_090.ml
                ./filesystems_091.ml ./filesystems_092.ml
                ./filesystems_093.ml ./filesystems_094.ml
                ./filesystems_095.ml ./filesystems_096.ml
                ./filesystems_097.ml ./filesystems_098.ml
                ./filesystems_099.ml ./filesystems_100.ml
                ./filesystems_101.ml ./filesystems_102.ml
                ./filesystems_103.ml ./filesystems_104.ml
                ./filesystems_105.ml ./filesystems_106.ml
                ./filesystems_107.ml ./filesystems_108.ml
                ./filesystems_109.ml ./filesystems_110.ml
                ./filesystems_111.ml ./filesystems_112.ml
                ./filesystems_113.ml ./filesystems_114.ml
                ./filesystems_115.ml ./llvm.ml ./dyadic.ml ./ctf.ml ./rpi.ml
                ./linux.ml ./nitpicker.ml ./mail_news.ml ./commands.ml
                ./glibc.ml ./wsdl.ml ./tcl.ml ./msooxml.ml ./ruby.ml
                ./hitachi_sh.ml ./git.ml ./ssh.ml ./oasis.ml ./luks.ml
                ./clojure.ml ./plan9.ml ./rinex.ml ./zfs.ml ./keepass.ml
                ./nasa.ml ./warc.ml ./asf.ml ./guile.ml ./sketch.ml ./dact.ml
                ./sequent.ml ./compress.ml ./xenix.ml ./audio.ml ./osf1.ml
                ./vax.ml ./isz.ml ./wordprocessors.ml ./grace.ml ./pdp.ml
                ./basis.ml ./bsi.ml ./varied_out.ml ./human68k.ml ./att3b.ml
                ./sosi.ml ./ispell.ml ./blender.ml ./claris.ml ./octave.ml
                ./apple.ml ./edid.ml ./yara.ml ./fcs.ml ./mathematica.ml
                ./msvc.ml ./coverage.ml ./spec.ml ./mozilla.ml ./jpeg.ml
                ./sc.ml ./wireless.ml ./apl.ml ./lex.ml ./java.ml
                ./varied_script.ml ./terminfo.ml ./numpy.ml ./olf.ml
                ./btsnoop.ml ./marc21.ml ./cbor.ml ./coff.ml ./pmem.ml
                ./frame.ml ./mach.ml ./bioinformatics.ml ./lecter.ml
                ./lisp.ml ./island.ml ./c64.ml ./cddb.ml ./pgp.ml
                ./hardware.ml ./mmdf.ml ./m4.ml ./tplink.ml ./qt.ml ./gnu.ml
                ./mcrypt.ml ./xdelta.ml ./beetle.ml ./fusecompress.ml
                ./archive.ml ./lua.ml ./zyxel.ml ./apt.ml ./gnumeric.ml
                ./zip.ml ./pc98.ml ./cracklib.ml ./printer.ml ./chord.ml
                ./cubemap.ml ./citrus.ml ./blit.ml ./editors.ml ./gcc.ml
                ./rst.ml ./vacuum_cleaner.ml ./unicode.ml ./riff.ml
                ./ole2compounddocs.ml ./epoc.ml ./fsav.ml ./kicad.ml
                ./ocaml.ml ./fortran.ml ./netware.ml ./application.ml
                ./windows.ml ./openfst.ml ./hp.ml ./xwindows.ml ./vmware.ml
                ./pwsafe.ml ./inform.ml ./plus5.ml ./elf.ml ./ibm370.ml
                ./amanda.ml ./measure.ml ./ebml.ml ./alliant.ml
                ./meteorological.ml ./geo.ml ./pbf.ml ./make.ml ./psl.ml
                ./pkgadd.ml ./scientific.ml ./sniffer.ml ./music.ml
                ./softquad.ml ./neko.ml ./mips.ml ./macos.ml ./gpt.ml
                ./magic.ml ./timezone.ml ./spectrum.ml ./sgml.ml ./sccs.ml
                ./sendmail.ml ./ti_8x.ml ./modem.ml ./gimp.ml ./database.ml
                ./unknown.ml ./uuencode.ml ./console.ml ./mercurial.ml
                ./sgi.ml ./erlang.ml ./communications.ml ./sisu.ml ./mime.ml
                ./blcr.ml ./misctools.ml ./parix.ml ./troff.ml ./psdbms.ml
                ./convex.ml ./webassembly.ml ./microfocus.ml ./sharc.ml
                ./vicar.ml ./rpmsg.ml ./msx.ml ./acorn.ml ./tex.ml ./fonts.ml
                ./sysex.ml ./biosig.ml ./parrot.ml ./pc88.ml ./tgif.ml
                ./vms.ml)
 (deps %{bin:conan.serialize} (source_tree ../database))
 (action
  (run conan.serialize ../database -o .)))

(library
 (name conan_database)
 (modules 
conan_database blackberry os2 bout kerberos os400 diamond amigaos graphviz
uterus cad cisco macintosh cups zilog clarion mathcad ibm6000 motorola efi
virtutech clipper flif xilinx c_lang symbos finger vxl dataone sql pascal
modulefile teapot forth news virtual' images images_000 images_001 images_002
images_003 images_004 images_005 images_006 images_007 images_008 images_009
images_010 images_011 images_012 images_013 images_014 images_015 images_016
images_017 images_018 images_019 images_020 images_021 images_022 images_023
images_024 images_025 images_026 images_027 images_028 images_029 images_030
images_031 images_032 images_033 images_034 images_035 images_036 images_037
images_038 images_039 images_040 images_041 images_042 images_043 images_044
images_045 images_046 images_047 images_048 images_049 images_050 images_051
images_052 images_053 images_054 images_055 images_056 images_057 images_058
images_059 images_060 images_061 images_062 images_063 images_064 images_065
images_066 images_067 images_068 images_069 images_070 images_071 images_072
images_073 images_074 images_075 images_076 images_077 images_078 images_079
images_080 images_081 images_082 images_083 images_084 images_085 images_086
images_087 images_088 images_089 images_090 images_091 images_092 images_093
images_094 images_095 images_096 images_097 images_098 images_099 images_100
images_101 images_102 images_103 images_104 images_105 images_106 images_107
images_108 images_109 images_110 images_111 images_112 images_113 images_114
images_115 images_116 images_117 images_118 images_119 images_120 images_121
images_122 images_123 images_124 images_125 images_126 images_127 images_128
images_129 images_130 images_131 images_132 images_133 images_134 images_135
images_136 images_137 images_138 images_139 images_140 images_141 images_142
images_143 images_144 images_145 images_146 images_147 images_148 images_149
images_150 images_151 images_152 images_153 images_154 images_155 images_156
images_157 images_158 images_159 images_160 images_161 images_162 images_163
images_164 images_165 images_166 images_167 images_168 images_169 images_170
images_171 images_172 images_173 images_174 bsdi rtf freebsd visx flash mkid
metastore bflt palm intel ctags esri dump interleaf adventure animation adi
sinclair matroska geos netscape algol68 digital mup gconv lif asterix natinst
apache cafebabe dolby bhl iff icc mlssa karma kml selinux python perl pyramid
msdos games ncr smalltalk weak dbpf assembler mirage os9 ssl revision map
polyml diff smile maple der encore etf securitycerts espressif typeset pulsar
opentimestamps pgf allegro x68000 sereal aout pbm rpm kde netbsd alpha
javascript vorbis android gringotts applix tuxedo pdf gnome sun ber xo65 gpu
project filesystems filesystems_000 filesystems_001 filesystems_002
filesystems_003 filesystems_004 filesystems_005 filesystems_006
filesystems_007 filesystems_008 filesystems_009 filesystems_010
filesystems_011 filesystems_012 filesystems_013 filesystems_014
filesystems_015 filesystems_016 filesystems_017 filesystems_018
filesystems_019 filesystems_020 filesystems_021 filesystems_022
filesystems_023 filesystems_024 filesystems_025 filesystems_026
filesystems_027 filesystems_028 filesystems_029 filesystems_030
filesystems_031 filesystems_032 filesystems_033 filesystems_034
filesystems_035 filesystems_036 filesystems_037 filesystems_038
filesystems_039 filesystems_040 filesystems_041 filesystems_042
filesystems_043 filesystems_044 filesystems_045 filesystems_046
filesystems_047 filesystems_048 filesystems_049 filesystems_050
filesystems_051 filesystems_052 filesystems_053 filesystems_054
filesystems_055 filesystems_056 filesystems_057 filesystems_058
filesystems_059 filesystems_060 filesystems_061 filesystems_062
filesystems_063 filesystems_064 filesystems_065 filesystems_066
filesystems_067 filesystems_068 filesystems_069 filesystems_070
filesystems_071 filesystems_072 filesystems_073 filesystems_074
filesystems_075 filesystems_076 filesystems_077 filesystems_078
filesystems_079 filesystems_080 filesystems_081 filesystems_082
filesystems_083 filesystems_084 filesystems_085 filesystems_086
filesystems_087 filesystems_088 filesystems_089 filesystems_090
filesystems_091 filesystems_092 filesystems_093 filesystems_094
filesystems_095 filesystems_096 filesystems_097 filesystems_098
filesystems_099 filesystems_100 filesystems_101 filesystems_102
filesystems_103 filesystems_104 filesystems_105 filesystems_106
filesystems_107 filesystems_108 filesystems_109 filesystems_110
filesystems_111 filesystems_112 filesystems_113 filesystems_114
filesystems_115 llvm dyadic ctf rpi linux nitpicker mail_news commands glibc
wsdl tcl msooxml ruby hitachi_sh git ssh oasis luks clojure plan9 rinex zfs
keepass nasa warc asf guile sketch dact sequent compress xenix audio osf1 vax
isz wordprocessors grace pdp basis bsi varied_out human68k att3b sosi ispell
blender claris octave apple edid yara fcs mathematica msvc coverage spec
mozilla jpeg sc wireless apl lex java varied_script terminfo numpy olf
btsnoop marc21 cbor coff pmem frame mach bioinformatics lecter lisp island
c64 cddb pgp hardware mmdf m4 tplink qt gnu mcrypt xdelta beetle fusecompress
archive lua zyxel apt gnumeric zip pc98 cracklib printer chord cubemap citrus
blit editors gcc rst vacuum_cleaner unicode riff ole2compounddocs epoc fsav
kicad ocaml fortran netware application windows openfst hp xwindows vmware
pwsafe inform plus5 elf ibm370 amanda measure ebml alliant meteorological geo
pbf make psl pkgadd scientific sniffer music softquad neko mips macos gpt
magic timezone spectrum sgml sccs sendmail ti_8x modem gimp database unknown
uuencode console mercurial sgi erlang communications sisu mime blcr misctools
parix troff psdbms convex webassembly microfocus sharc vicar rpmsg msx acorn
tex fonts sysex biosig parrot pc88 tgif vms)
 (libraries conan))
